'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.3053
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DEMANDE_ACHAT.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _19486() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("19486", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property billetage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("billetage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btAjouter22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btAjouter22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btAjouter221() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btAjouter221", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btAjouter222() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btAjouter222", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btAjouter32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btAjouter32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btApercu22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btApercu22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btApercu32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btApercu32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btEnregistrer22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btEnregistrer22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btEnregistrer32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btEnregistrer32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btFermer22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btFermer22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btFermer32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btFermer32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btFiltre22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btFiltre22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btFiltre32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btFiltre32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btFlecheBas32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btFlecheBas32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btFlecheHaut32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btFlecheHaut32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btImprimer22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btImprimer22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btImprimer32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btImprimer32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btInfo32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btInfo32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btModifier22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btModifier22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btModifier32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btModifier32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btn_valider() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_valider", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btRepertoireA22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btRepertoireA22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btRepertoireA32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btRepertoireA32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btRepertoireB22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btRepertoireB22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btRepertoireB32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btRepertoireB32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btRetour22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btRetour22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btRetour32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btRetour32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btSupprimer22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btSupprimer22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btSupprimer32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btSupprimer32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Configuration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Configuration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property e_mail_enveloppe_icone_9553_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("e-mail-enveloppe-icone-9553-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_bleu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_bleu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ExEtranger_frm_BackgroundImage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExEtranger_frm.BackgroundImage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fichiers_ini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fichiers ini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property foldeopen_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("foldeopen_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icone_imprimer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icone_imprimer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Image2_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image2.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Image7_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image7.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_waza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_waza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loupe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loupe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NoVehicule() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NoVehicule", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Papier_peint_Waza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Papier peint Waza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property quitter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quitter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property quitter1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quitter1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sortie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sortie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property votre_solution_sage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("votre_solution_sage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property votre_solution_sage_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("votre_solution_sage copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WazaSolutions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WazaSolutions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
